"""
LD3-D Trainer: Learning to Discretize Discrete Diffusion.

Learns optimal timestep schedules for discrete diffusion models by optimizing
N+1 scalar parameters (softmax + cumsum parameterization) via differentiable
probability-flow tracking.

Architecture mirrors LD3's trainer.py but adapted for discrete state spaces:
  - Phase 1: Learn coarse schedule (params1 via RMSprop)
  - Phase 2: Fine-tune with perturbations (params1 + params2)
  - Probability-flow loss replaces LPIPS loss
  - Cross-entropy / perplexity metrics replace FID

Reference: LD3-D Proposal (LD3_D_PROPOSAL.md)
"""

from typing import List, Optional
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

import logging
import os
import math
import pickle
import numpy as np
import matplotlib.pyplot as plt

from discrete_noise_schedulers import DiscreteNoiseSchedule


# ============================================================================
# Dataset for Discrete Diffusion
# ============================================================================

class DiscreteLD3Dataset(Dataset):
    """Dataset for LD3-D training.

    Each sample contains:
      - tokens_teacher: Clean tokens generated by teacher (many-step sampler) [L]
      - noise_tokens: Initial noisy tokens (all-mask or random) [L]
      - condition: Optional conditioning information
    """

    def __init__(self, noise_tokens, tokens_teacher, conditions=None):
        self.noise_tokens = noise_tokens      # List of [L] tensors
        self.tokens_teacher = tokens_teacher  # List of [L] tensors
        self.conditions = conditions          # List of tensors or None

    def __len__(self):
        return len(self.noise_tokens)

    def __getitem__(self, idx):
        noise = self.noise_tokens[idx]
        teacher = self.tokens_teacher[idx]
        cond = self.conditions[idx] if self.conditions is not None else None
        return noise, teacher, cond


def discrete_collate_fn(batch):
    """Custom collate for variable-length sequences."""
    noises, teachers, conds = zip(*batch)
    noises = torch.stack(noises)
    teachers = torch.stack(teachers)
    if conds[0] is not None:
        conds = torch.stack(conds)
    else:
        conds = None
    return noises, teachers, conds


# ============================================================================
# Configuration Dataclasses
# ============================================================================

@dataclass
class DiscreteModelConfig:
    """Configuration for the discrete diffusion model."""
    net: nn.Module                        # Pre-trained score model
    noise_schedule: DiscreteNoiseSchedule # Discrete noise schedule
    solver: object                        # Discrete sampler (tau-leaping, analytic, etc.)
    diffusion_type: str = 'absorbing'     # 'absorbing', 'uniform', or 'flow'
    steps: int = 32                       # Number of sampling steps (NFE budget)
    vocab_size: int = 32000               # Vocabulary size K
    seq_length: int = 256                 # Sequence length L
    time_mode: str = 'time'               # 'time' or 'rate_integral'
    snapshot_path: str = 'logs_discrete'
    device: Optional[str] = None


@dataclass
class DiscreteTrainingConfig:
    """Configuration for LD3-D training."""
    train_data: DiscreteLD3Dataset
    valid_data: DiscreteLD3Dataset
    train_batch_size: int = 8
    valid_batch_size: int = 8
    lr_time_1: float = 0.005        # Phase 1 learning rate
    lr_time_2: float = 0.1          # Phase 2 learning rate (per step)
    min_lr_time_1: float = 5e-5
    min_lr_time_2: float = 1e-6
    win_rate: float = 0.5           # Perturbation window rate
    patient: int = 5                # Patience for LR decay
    lr2_patient: int = 5
    lr_time_decay: float = 0.8
    momentum_time_1: float = 0.9
    loss_type: str = 'cross_entropy'  # 'cross_entropy', 'kl', 'l2', 'perplexity'
    theory_proxy_weight: float = 0.0  # Weight for theory-motivated proxy loss
    temperature: float = 1.0          # Temperature for probability flow
    training_rounds_v1: int = 3       # Phase 1 rounds
    training_rounds_v2: int = 5       # Phase 2 rounds


# ============================================================================
# Discretize Model Wrapper (adapted from LD3)
# ============================================================================

def discrete_discretize_model_wrapper(input1, input2, t_max, t_min,
                                       noise_schedule, mode, window_rate=0.5):
    """Create a differentiable timestep schedule from learnable parameters.

    Same parameterization as LD3 but for discrete diffusion time domain.

    For discrete diffusion:
      - time mode: timesteps in [eps, T] (corruption time)
      - rate_integral mode: timesteps mapped via rate integral space

    Args:
        input1: params1 (softmax weights), shape [N+1]
        input2: params2 (perturbations), shape [N+1]
        t_max: Maximum time (T)
        t_min: Minimum time (eps)
        noise_schedule: DiscreteNoiseSchedule
        mode: 'time' or 'rate_integral'
        window_rate: Maximum perturbation as fraction of minimum gap

    Returns:
        A callable that returns (timesteps1, timesteps2)
    """

    def model_time_fn():
        """Schedule parameterization in time space."""
        time1, time2 = input1, input2

        # Softmax -> cumsum -> monotonic mapping to [t_max, t_min]
        time_plus = F.softmax(time1, dim=0)
        time_md = torch.cumsum(time_plus, dim=0).flip(0)  # Decreasing
        normed = (time_md - time_md[-1]) / (time_md[0] - time_md[-1] + 1e-10)
        time_steps = normed * (t_max - t_min) + t_min

        # Perturbations
        cloned_time_steps = time_steps.clone().detach()
        gaps = (cloned_time_steps[:-1] - cloned_time_steps[1:]).abs()
        max_move = gaps.min().item() * window_rate if len(gaps) > 0 else 0.01
        clipped_time2 = torch.clamp(time2, min=-max_move, max=max_move)

        # Mask: don't perturb endpoints
        mask = torch.ones_like(normed)
        mask[0] = 0.0
        mask[-1] = 0.0

        return time_steps, time_steps + (clipped_time2 * mask)

    def model_rate_integral_fn():
        """Schedule parameterization in rate-integral space.

        Analogous to LD3's lambda (logSNR) mode but using
        the rate integral v(t) = integral_0^t sigma(s) ds.
        """
        v1, v2 = input1, input2

        # Compute rate integral bounds
        v_max_val = noise_schedule.rate_integral(torch.tensor(t_max, dtype=torch.float64)).float()
        v_min_val = noise_schedule.rate_integral(torch.tensor(t_min, dtype=torch.float64)).float()
        v_max_val = v_max_val.to(input1.device)
        v_min_val = v_min_val.to(input1.device)

        # Softmax -> cumsum in rate-integral space
        v_plus = F.softmax(v1, dim=0)
        v_md = torch.cumsum(v_plus, dim=0)
        normed = (v_md - v_md.min()) / (v_md.max() - v_md.min() + 1e-10)
        v_steps1 = normed * (v_max_val - v_min_val) + v_min_val

        # Perturbations in rate-integral space
        cloned_v1 = v1.clone().detach()
        gaps = (cloned_v1[1:] - cloned_v1[:-1]).abs()
        max_move = gaps.min().item() * window_rate if len(gaps) > 0 else 0.01
        clipped_v2 = torch.clamp(v2, min=-max_move, max=max_move)

        mask = torch.ones_like(v_steps1)
        mask[0] = 0.0
        mask[-1] = 0.0
        v_steps2 = v_steps1 + clipped_v2 * mask

        # Convert back to time
        time1 = noise_schedule.inverse_rate_integral(v_steps1.double()).float()
        time2 = noise_schedule.inverse_rate_integral(v_steps2.double()).float()

        return time1, time2

    return model_time_fn if mode == 'time' else model_rate_integral_fn


# ============================================================================
# LD3-D Trainer
# ============================================================================

class LD3DTrainer:
    """Trainer for learning optimal discrete diffusion schedules.

    Optimizes timestep schedule parameters (params1, params2) by tracking
    the reverse process in probability space and minimizing reconstruction
    loss against teacher-generated outputs.
    """

    def __init__(self, model_config: DiscreteModelConfig,
                 training_config: DiscreteTrainingConfig):

        # Model components
        self.net = model_config.net
        self.noise_schedule = model_config.noise_schedule
        self.solver = model_config.solver
        self.diffusion_type = model_config.diffusion_type
        self.steps = model_config.steps
        self.K = model_config.vocab_size
        self.L = model_config.seq_length
        self.time_mode = model_config.time_mode
        self.snapshot_path = model_config.snapshot_path
        os.makedirs(self.snapshot_path, exist_ok=True)

        # Training data
        self.train_data = training_config.train_data
        self.valid_data = training_config.valid_data
        self.train_batch_size = training_config.train_batch_size
        self.valid_batch_size = training_config.valid_batch_size
        self._create_data_loaders()

        # Training hyperparameters
        self.lr_time_1 = training_config.lr_time_1
        self.lr_time_2 = training_config.lr_time_2
        self.min_lr_time_1 = training_config.min_lr_time_1
        self.min_lr_time_2 = training_config.min_lr_time_2
        self.lr_time_decay = training_config.lr_time_decay
        self.win_rate = training_config.win_rate
        self.patient = training_config.patient
        self.lr2_patient = training_config.lr2_patient
        self.loss_type = training_config.loss_type
        self.theory_proxy_weight = training_config.theory_proxy_weight
        self.temperature = training_config.temperature
        self.training_rounds_v1 = training_config.training_rounds_v1
        self.training_rounds_v2 = training_config.training_rounds_v2

        # Device
        self.device = model_config.device or torch.device(
            'cuda' if torch.cuda.is_available() else 'cpu'
        )

        # Initialize learnable parameters
        self.params1, self.params2 = self._initialize_params()

        # Optimizers
        self.optimizer1 = torch.optim.RMSprop(
            [self.params1], lr=self.lr_time_1,
            momentum=training_config.momentum_time_1
        )
        self.optimizer2 = torch.optim.SGD(
            [self.params2], lr=self.lr_time_2 / max(self.steps, 1)
        )

        # Time bounds
        self.t_max = self.noise_schedule.T
        self.t_min = self.noise_schedule.eps

        # Training state
        self.cur_iter = 0
        self.cur_round = 0
        self.count_worse = 0
        self.count_min_lr1_hit = 0
        self.count_min_lr2_hit = 0
        self.best_loss = float('inf')

        # Compute baselines for visualization
        self._compute_baselines()

    def _initialize_params(self):
        """Initialize schedule parameters."""
        params1 = nn.Parameter(
            torch.ones(self.steps + 1, dtype=torch.float32, device=self.device),
            requires_grad=True
        )
        params2 = nn.Parameter(
            torch.zeros(self.steps + 1, dtype=torch.float32, device=self.device),
            requires_grad=True
        )
        return params1, params2

    def _create_data_loaders(self):
        self.train_loader = DataLoader(
            self.train_data, batch_size=self.train_batch_size,
            shuffle=True, collate_fn=discrete_collate_fn
        )
        self.valid_loader = DataLoader(
            self.valid_data, batch_size=self.valid_batch_size,
            shuffle=False, collate_fn=discrete_collate_fn
        )

    def _compute_baselines(self):
        """Compute baseline schedules for comparison."""
        N = self.steps
        # Uniform in time
        self.baseline_uniform = torch.linspace(self.t_max, self.t_min, N + 1)
        # Uniform in rate integral
        v_max = self.noise_schedule.rate_integral(torch.tensor(self.t_max)).item()
        v_min = self.noise_schedule.rate_integral(torch.tensor(self.t_min)).item()
        v_uniform = torch.linspace(v_max, v_min, N + 1)
        self.baseline_rate_uniform = self.noise_schedule.inverse_rate_integral(
            v_uniform.double()
        ).float()
        # Quadratic
        ramp = torch.linspace(0, 1, N + 1)
        self.baseline_quadratic = self.t_min + (self.t_max - self.t_min) * (1 - ramp) ** 2

    def _get_schedule(self):
        """Get current timestep schedule from learnable parameters."""
        dis_model = discrete_discretize_model_wrapper(
            self.params1, self.params2,
            self.t_max, self.t_min,
            self.noise_schedule, self.time_mode, self.win_rate
        )
        return dis_model()

    def _run_probability_flow(self, noise_tokens, condition=None):
        """Run reverse process in probability space.

        Args:
            noise_tokens: Initial noisy tokens [B, L]
            condition: Optional conditioning

        Returns:
            p_final: Final probability distribution [B, L, K]
            timesteps1, timesteps2: Schedules used
        """
        B, L = noise_tokens.shape
        timesteps1, timesteps2 = self._get_schedule()

        # Initialize probability distribution
        if self.diffusion_type == 'absorbing':
            # Start with all probability on MASK
            mask_idx = self.noise_schedule.mask_index
            p_init = torch.zeros(B, L, self.K, device=self.device)
            p_init[:, :, mask_idx] = 1.0
        elif self.diffusion_type == 'uniform':
            # Start with uniform distribution
            p_init = torch.ones(B, L, self.K, device=self.device) / self.K
        else:
            p_init = torch.ones(B, L, self.K, device=self.device) / self.K

        # Run probability flow
        from discrete_samplers.probability_flow import ProbabilityFlowSolver
        pf_solver = ProbabilityFlowSolver(
            self.noise_schedule, self.diffusion_type, self.temperature
        )

        def score_fn(p, t, condition=None):
            """Score function for probability flow."""
            if hasattr(self.net, 'soft'):
                return self.net.soft(p, t, condition)
            else:
                return self.net(p, t, condition)

        p_final = pf_solver.sample_probability_flow(
            score_fn, p_init, timesteps1, timesteps2, condition
        )

        return p_final, timesteps1, timesteps2

    def _compute_loss(self, p_final, targets, timesteps1=None):
        """Compute loss between predicted distribution and teacher targets.

        Args:
            p_final: Predicted distributions [B, L, K]
            targets: Teacher token indices [B, L]
            timesteps1: Schedule (for theory proxy loss)

        Returns:
            loss: Scalar loss
        """
        B, L, K = p_final.shape

        # Reconstruction loss
        if self.loss_type == 'cross_entropy':
            log_probs = torch.log(p_final + 1e-10)
            target_log_probs = log_probs.gather(
                dim=-1, index=targets.unsqueeze(-1)
            ).squeeze(-1)
            recon_loss = -target_log_probs.mean()

        elif self.loss_type == 'perplexity':
            # Perplexity = exp(cross_entropy)
            log_probs = torch.log(p_final + 1e-10)
            target_log_probs = log_probs.gather(
                dim=-1, index=targets.unsqueeze(-1)
            ).squeeze(-1)
            recon_loss = -target_log_probs.mean()
            # Return CE; perplexity is for reporting

        elif self.loss_type == 'kl':
            target_one_hot = F.one_hot(targets, K).float()
            log_probs = torch.log(p_final + 1e-10)
            kl = (target_one_hot * (torch.log(target_one_hot + 1e-10) - log_probs))
            recon_loss = kl.sum(dim=-1).mean()

        elif self.loss_type == 'l2':
            target_one_hot = F.one_hot(targets, K).float()
            recon_loss = ((p_final - target_one_hot) ** 2).sum(dim=-1).mean()

        else:
            raise ValueError(f"Unknown loss_type: {self.loss_type}")

        # Theory proxy loss (optional regularizer)
        total_loss = recon_loss
        if self.theory_proxy_weight > 0 and timesteps1 is not None:
            proxy_loss = self._compute_theory_proxy(timesteps1)
            total_loss = total_loss + self.theory_proxy_weight * proxy_loss

        return total_loss

    def _compute_theory_proxy(self, timesteps):
        """Compute theory-motivated proxy: sum_i h_i^2 * C_i.

        C_i estimates the rate-of-change of the reverse rate at t_i.
        """
        N = len(timesteps) - 1
        loss = torch.tensor(0.0, device=self.device)

        for i in range(N):
            h_i = (timesteps[i] - timesteps[i + 1]).abs()
            t_i = timesteps[i]

            # Estimate C_i from rate function curvature
            sigma_i = self.noise_schedule.rate_scalar(t_i)
            dt = 1e-3 * self.t_max
            sigma_ip = self.noise_schedule.rate_scalar(t_i + dt)

            if isinstance(sigma_i, torch.Tensor):
                sigma_i = sigma_i.to(self.device)
            if isinstance(sigma_ip, torch.Tensor):
                sigma_ip = sigma_ip.to(self.device)

            dsigma = ((sigma_ip - sigma_i) / dt) ** 2
            loss = loss + h_i ** 2 * dsigma

        return loss

    @property
    def _current_version(self):
        return 'Phase1' if self.cur_round < self.training_rounds_v1 else 'Phase2'

    def _set_trainable(self):
        """Set which parameters are trainable based on current phase."""
        if self.cur_round < self.training_rounds_v1:
            self.params1.requires_grad = True
            self.params2.requires_grad = False
        else:
            self.params1.requires_grad = True
            self.params2.requires_grad = True

    def _run_validation(self):
        """Run validation and return average loss."""
        total_loss = 0.0
        count = 0

        with torch.no_grad():
            for noise_tokens, teacher_tokens, condition in self.valid_loader:
                noise_tokens = noise_tokens.to(self.device)
                teacher_tokens = teacher_tokens.to(self.device)
                if condition is not None:
                    condition = condition.to(self.device)

                p_final, ts1, ts2 = self._run_probability_flow(
                    noise_tokens, condition
                )
                loss = self._compute_loss(p_final, teacher_tokens, ts1)
                total_loss += loss.item()
                count += 1

        return total_loss / max(count, 1)

    def _save_checkpoint(self):
        """Save best model checkpoint."""
        checkpoint = {
            'params1': self.params1.data.cpu(),
            'params2': self.params2.data.cpu(),
            'best_t_steps': torch.cat([
                self._get_schedule()[0].detach().cpu(),
                self._get_schedule()[1].detach().cpu()
            ]),
            'best_loss': self.best_loss,
            'cur_round': self.cur_round,
            'cur_iter': self.cur_iter,
        }
        path = os.path.join(self.snapshot_path, 'best_discrete.pt')
        torch.save(checkpoint, path)
        logging.info(f"Checkpoint saved to {path}")

    def _load_checkpoint(self):
        """Load best model checkpoint."""
        path = os.path.join(self.snapshot_path, 'best_discrete.pt')
        if os.path.exists(path):
            checkpoint = torch.load(path, map_location=self.device)
            self.params1.data = checkpoint['params1'].to(self.device)
            self.params2.data = checkpoint['params2'].to(self.device)
            logging.info(f"Loaded checkpoint from {path}")

    def _visual_schedule(self):
        """Visualize the learned schedule vs. baselines."""
        timesteps1, timesteps2 = self._get_schedule()
        t1 = timesteps1.detach().cpu().numpy()
        t2 = timesteps2.detach().cpu().numpy()

        # Convert to corruption probability for more intuitive visualization
        beta1 = self.noise_schedule.marginal_prob(
            torch.tensor(t1, dtype=torch.float64)
        ).numpy()
        beta2 = self.noise_schedule.marginal_prob(
            torch.tensor(t2, dtype=torch.float64)
        ).numpy()

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Plot 1: Timesteps
        x_axis = np.arange(len(t1))
        axes[0].plot(x_axis, t1, 'o-', label='Learned (primary)', markersize=4)
        axes[0].plot(x_axis, t2, 'x-', label='Learned (perturbed)', markersize=4)
        axes[0].plot(x_axis, self.baseline_uniform.numpy(), '--',
                     label='Uniform', alpha=0.7)
        axes[0].plot(x_axis, self.baseline_rate_uniform.numpy(), '--',
                     label='Rate-uniform', alpha=0.7)
        axes[0].plot(x_axis, self.baseline_quadratic.numpy(), '--',
                     label='Quadratic', alpha=0.7)
        axes[0].set_xlabel('Reverse step i')
        axes[0].set_ylabel('Time t_i')
        axes[0].set_title('Timestep Schedule')
        axes[0].legend(fontsize=8)

        # Plot 2: Step sizes
        h1 = np.abs(np.diff(t1))
        h_uniform = np.abs(np.diff(self.baseline_uniform.numpy()))
        axes[1].bar(np.arange(len(h1)), h1, alpha=0.7, label='Learned')
        axes[1].plot(np.arange(len(h_uniform)), h_uniform, 'r--',
                     label='Uniform', linewidth=2)
        axes[1].set_xlabel('Step i')
        axes[1].set_ylabel('Step size h_i')
        axes[1].set_title('Step Size Allocation')
        axes[1].legend(fontsize=8)

        plt.tight_layout()
        path = os.path.join(self.snapshot_path,
                            f'schedule_iter{self.cur_iter}.png')
        plt.savefig(path, dpi=150)
        plt.close()
        logging.info(f"Schedule visualization saved to {path}")

    def _examine_checkpoint(self):
        """Evaluate, save if improved, decay LR if plateau."""
        val_loss = self._run_validation()
        logging.info(f"{self._current_version} Iter {self.cur_iter} | "
                     f"Val loss: {val_loss:.6f} | Best: {self.best_loss:.6f}")

        if val_loss < self.best_loss:
            self.best_loss = val_loss
            self.count_worse = 0
            self._save_checkpoint()
            self._visual_schedule()
        else:
            self.count_worse += 1

        if self.count_worse >= self.patient:
            self._load_checkpoint()
            self.count_worse = 0

            # Decay learning rates
            new_lr1 = max(
                self.lr_time_decay * self.optimizer1.param_groups[0]['lr'],
                self.min_lr_time_1
            )
            self.optimizer1.param_groups[0]['lr'] = new_lr1
            logging.info(f"Decayed LR1 to {new_lr1}")

            if self.cur_round >= self.training_rounds_v1:
                new_lr2 = max(
                    self.lr_time_decay * self.optimizer2.param_groups[0]['lr'],
                    self.min_lr_time_2
                )
                self.optimizer2.param_groups[0]['lr'] = new_lr2
                logging.info(f"Decayed LR2 to {new_lr2}")

                if new_lr2 <= self.min_lr_time_2:
                    self.count_min_lr2_hit += 1

    def _train_one_round(self):
        """Train for one round (one pass through training data)."""
        logging.info(f"{self._current_version} Starting round {self.cur_round}")

        if self.cur_round > 0:
            self._load_checkpoint()
            self.count_worse = 0

        self._set_trainable()
        self._examine_checkpoint()

        for noise_tokens, teacher_tokens, condition in self.train_loader:
            noise_tokens = noise_tokens.to(self.device)
            teacher_tokens = teacher_tokens.to(self.device)
            if condition is not None:
                condition = condition.to(self.device)

            # Forward: probability flow with current schedule
            self.optimizer1.zero_grad()
            self.optimizer2.zero_grad()

            p_final, ts1, ts2 = self._run_probability_flow(
                noise_tokens, condition
            )
            loss = self._compute_loss(p_final, teacher_tokens, ts1)

            # Backward
            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_([self.params1], 1.0)
            torch.nn.utils.clip_grad_norm_([self.params2], 1.0)

            # Update
            self.optimizer1.step()
            if self.cur_round >= self.training_rounds_v1:
                self.optimizer2.step()

            self.cur_iter += 1
            logging.info(f"{self._current_version} Iter {self.cur_iter} | "
                         f"Train loss: {loss.item():.6f}")

            # Periodic evaluation
            self._examine_checkpoint()

            if self.count_min_lr2_hit >= self.lr2_patient:
                logging.info("Reached minimum LR2 limit. Stopping.")
                return True  # should_stop

        return False

    def train(self):
        """Main training loop.

        Phase 1: Learn coarse schedule (params1 only)
        Phase 2: Fine-tune with perturbations (params1 + params2)
        """
        total_rounds = self.training_rounds_v1 + self.training_rounds_v2

        logging.info(f"Starting LD3-D training: {total_rounds} rounds "
                     f"({self.training_rounds_v1} phase1 + {self.training_rounds_v2} phase2)")
        logging.info(f"NFE budget: {self.steps} steps | "
                     f"Vocab: {self.K} | Seq length: {self.L}")
        logging.info(f"Diffusion type: {self.diffusion_type} | "
                     f"Time mode: {self.time_mode}")

        while self.cur_round < total_rounds:
            should_stop = self._train_one_round()
            if should_stop:
                break
            self.cur_round += 1

        # Final evaluation
        logging.info("Training complete. Final evaluation:")
        final_loss = self._run_validation()
        logging.info(f"Final validation loss: {final_loss:.6f}")

        # Log learned schedule
        ts1, ts2 = self._get_schedule()
        logging.info(f"Learned schedule (primary): {ts1.detach().cpu().tolist()}")
        logging.info(f"Learned schedule (perturbed): {ts2.detach().cpu().tolist()}")

        self._visual_schedule()

    def get_learned_schedule(self):
        """Return the learned timestep schedule."""
        self._load_checkpoint()
        return self._get_schedule()
